//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXMLReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Laptops = new HashSet<Laptop>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CPU { get; set; }
        public int RAM { get; set; }
        public int HDD { get; set; }
    
        public virtual ICollection<Laptop> Laptops { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
